"""add semester to course

Revision ID: 016022a53351
Revises: 8c5231a5f723
Create Date: 2025-07-18 17:36:40.813887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016022a53351'
down_revision = '8c5231a5f723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('semester')

    # ### end Alembic commands ###
